config/routes.rb
Rails.application.routes.draw do

  get 'auth/failure' => 'sessions#failure'
  get 'auth/:provider/callback' => 'sessions#create'
  # post 'auth/:provider/callback' => 'sessions#create'
  get 'auth/logout' => 'sessions#destroy', as: :auth_logout

  resources :gem_notes, path: :gems
  resources :gemfiles

  root 'home#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/gem_note.rb
# == Schema Information
#
# Table name: gem_notes
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  version     :string(255)
#  require     :string(255)
#  groups      :string(255)
#  platforms   :string(255)
#  source      :string(255)
#  git         :string(255)
#  github      :string(255)
#  path        :string(255)
#  description :text
#  state       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  branch      :string(255)
#  tag         :string(255)
#  ref         :string(255)
#  submodules  :string(255)
#  hashid      :string(255)
#  original    :string(255)
#  user_id     :integer
#

class GemNote < ActiveRecord::Base
  include Hashidable

  belongs_to :user

  acts_as_taggable

  validates :original, presence: true, allow_blank: false

  def active=(val)
    if val.to_i.zero?

      self.state = :disactived
    else
      self.state = :actived
    end
  end

  state_machine :state, initial: :active do
    event :disactive do
      transition actived: :disactived
    end

    event :active do
      transition disactived: :actived
    end
  end
end

app/controllers/gem_notes_controller.rb
class GemNotesController < ApplicationController
  before_action :gem_note_facade, except: [:destroy]
  before_action :set_gem_note, only: :destroy

  def index
    @facade.all
  end

  def create
    if @facade.create(gem_note_params)
      respond_to do |format|
        format.html { redirect_to :gem_notes }
        format.js { render json: { status: :success, code: 200, id: @facade.gem_note.id} }
      end
    else
      respond_to do |format|
        format.html do
          @facade.all
          render :index
        end
        format.js { render json: { status: :error, code: 500 } }
      end
    end
  end

  def update
    if @facade.update(gem_note_params)
      @facade.gem_note.reload
      respond_to do |format|
        format.html { redirect_to :gem_notes }
        format.js do
          render json: { status: :success,
                         code: 200,
                         id: @facade.gem_note.id,
                         original: @facade.gem_note.original,
                         description: @facade.gem_note.description,
                         active: @facade.gem_note.actived?
                 }
        end
      end
    else
      respond_to do |format|
        format.html do
          @facade.all
          render :index
        end
        format.js { render json: { status: :error, code: 500 } }
      end
    end
  end

  def destroy
    @gem_note.destroy
    respond_to do |format|
      format.html { redirect_to :gem_notes }
      format.js do
        render json: { status: :success, code: 200, id: @gem_note.id}
      end
    end
  end

  def show
    if params[:id].present?
      @facade.show params[:id]
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  private

  def gem_note_params
    { active: '0' }.merge params.require(:gem_note).permit(:original,
      :description,
      :active).merge(id: params[:id]).symbolize_keys
  end

  def gem_note_facade
    @facade = GemNotesFacade.new current_user
  end

  def set_gem_note
    # @facade.find(id: params[:id])
    @gem_note = GemNote.find_by(id: params[:id])
    render json: { status: :error, code: 404 } if @gem_note.nil?
  end
end

app/helpers/gem_notes_helper.rb
module GemNotesHelper
  def gem_active_class gemnote
    gemnote.actived? ? "actived" : ""
  end
end

app/views/gem_notes/_form.html.slim
.row.col-md-12.add-gem@@addGem
  .row.col-md-12.bg
    = simple_form_for @facade.gem_note, html: { class: 'form-gem form-inline' }, wraper_form: 'vertical_form' do |f|
      .row.main-values
        .col-md-10
          .row
            .col-md-12 =f.input :original, label: false, placeholder: t('gem.original'), class: 'original form-control'
          .row
            .col-md-12 =f.input :description, label: false, placeholder: t('gem.description'), \
              input_html: { class: 'description form-control' }
          /.row.col-md-12
            = f.association :tags, collection: @facade.tags, include_blank: true, input_html: { class: 'chosen-select form-control', multiple: true, style: 'width:350px;', data: { role: 'tags' } }

        .col-md-2
          .row.active-form
            .col-md-5
              label.title = t('gem.active')
            .col-md-6
              label.toggle
                = f.check_box :active, { checked: true }, '1', '0'
                span.handle

          .row.col-md-12.submit-btn@submitValues
            = submit_tag 'Add', class: 'btn btn-danger'

app/views/gem_notes/_gem_note.html.slim
= simple_form_for gem_note, html: { class: 'row col-md-12 gem-item', data: { block: 'gemItem' } }, wraper_form: 'vertical_form' do |f|
  .row.col-md-12.gem-item-link@linkGemField
    = text_field_tag 'gem-item-link', gem_note_url(gem_note.hashid), class: 'string form-control gem-field'
  .gem-item-line
    .row.main-row@main
      .col-md-1
        a.status@expandGemIcon class="#{gem_active_class(gem_note)} icon-anim" href="#"
          span.glyphicon.glyphicon-eye-open
        a.gem-edit.glyphicon.glyphicon-pencil.icon-anim.edit-gem@editGemIcon href="#"
        a.gem-edit.glyphicon.glyphicon-remove.icon-anim.cancel-edit-gem.hide@cancelEditGemIcon href="#"

      .col-md-8
        .origin-field@originField
        = f.text_field :original, class: 'mode-text param-name form-control', placeholder: t('gem.name'), disabled: 'disabled',  data: { role: 'editGemFields original', value: gem_note.original }
      .col-md-3.more
        = link_to '', gem_note_path(gem_note), class: 'gem-destroy glyphicon glyphicon-trash icon-anim', method: :delete, data: {confirm: "Delete item?"}

        a.gem-link.glyphicon.glyphicon-link.icon-anim@linkGemIcon href="#"
        = check_box_tag('gem_sected', gem_note.id, false, class: 'gem-select', data: { role: 'select' })
    .details@expandGemInfo
      .row
        .col-md-1.col-md-offset-0
          a.gem-edit.glyphicon.glyphicon-floppy-disk.icon-anim.update-edit-gem.hide@updateEditGemIcon href=gem_note_url(gem_note)
        .col-md-8
          = f.text_field :description, class: 'mode-text form-control', disabled: 'disabled', placeholder: t('gem.description'), data: {role: 'editGemFields description', value: gem_note.description }
        .col-md-1
          /label.title = t('gem.active')
        .col-md-2
          label.toggle
            = f.check_box :active, { disabled: true, data: { role: 'active', value: gem_note.actived? }, checked: gem_note.actived? }, '1', '0'
            /= check_box_tag :active, '1', gem_note.actived?, disabled: true, data: { role: 'active', value: gem_note.actived? }
            span.handle

app/views/gem_notes/index.html.slim
- content_for :navbar do
  = render 'layouts/navbar'

= render 'layouts/error_messages', object: @facade.gem_note
= render 'form'

.gem-list-container@@gemList

  - if @facade.gem_notes.any?
    .row.col-md-12.gem-list-operations
      .row
        .col-md-2.col.compose@composeGemfile data-action=gemfiles_path data-method='POST'
          | Compose Gemfile

    .row.col-md-12.gem-list-header
      .row
        .col-md-1.header-col Active
        .col-md-8.header-col Gem
        .col-md-3.header-col Operations
  - else
    .row.col-md-12
      .row.col-md-12.gem-list-empty Gem list empty

  .row.col-md-12.gem-list
    = render @facade.gem_notes
  .row.col-md-12
    hr

app/views/gem_notes/show.html.slim
.row.col-md-12
  .row
    .col-md-1 = t('gem.name')
    .col-md-8 = @facade.gem_note.original
  .row
    /.col-md-1 = t('gem.description')
    .col-md-8 = @facade.gem_note.description